### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by YaoJuan** [chipweinberger/flutter_blue_plus#1000]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.12

### Flutter Version

3.24.3

### What OS?

All

### OS Version

ios 17

### Bluetooth Module

esp32

### What is your problem?

Normally, I communicate with a packet size of 250 bytes, and in most cases, it works without any issues. However, occasionally, a normal packet (e.g., 65 bytes) gets split into 4 parts upon reception, like 20, 20, 20, and 5 bytes. This happens even though the MTU setting has not changed during the subscription.

### Logs

```shell
I/flutter (13172): [FBP] [[ OnCharacteristicReceived ]] result: {error_string: GATT_SUCCESS, service_uuid: 00f3, success: 1, remote_id: F0:F5:BD:77:A6:46, error_code: 0, characteristic_uuid: ae03, value: 24474e524d432c2c562c2c2c2c2c2c2c2c2c2c4e}
D/[FBP-Android](13172): [FBP] onCharacteristicChanged:
D/[FBP-Android](13172): [FBP]   chr: ae03
I/flutter (13172): [FBP] [[ OnCharacteristicReceived ]] result: {error_string: GATT_SUCCESS, service_uuid: 00f3, success: 1, remote_id: F0:F5:BD:77:A6:46, error_code: 0, characteristic_uuid: ae03, value: 2c562a33370d0a}
```

**Comment by chipweinberger** [comment]
this is a peripheral or iOS problem.

FBP cannot control this.
