### ISSUE TITLE
[Help]: BLE support on iOS: Unable to scan device after disconnect()

### ISSUE THREAD

**Issue by pnsang-goads** [chipweinberger/flutter_blue_plus#1005]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.32.12

### Flutter Version

3.22.2

### What OS?

iOS

### OS Version

IOS 15.8.1

### Bluetooth Module

Orange pi 3b

## Description
I’m encountering an issue with BLE on iOS. Specifically, when I use the `disconnect()` method, my app stops receiving data from the BLE device, but it also cannot scan the device again. As a workaround, I have to turn off and on the phone's Bluetooth, after which the device will be scanned immediately. I hope a solution can be provided for this issue.

## Steps to Reproduce
1. Connect to a BLE device on iOS.
2. Call the `disconnect()` method to disconnect the device.
3. Attempt to scan the BLE device again.

## Expected Behavior
The BLE device should be scannable after disconnecting without needing to toggle the phone’s Bluetooth.

## Actual Behavior
The app is unable to scan the device after disconnecting, requiring the Bluetooth to be turned off and on to scan the device again.

### Logs

```shell
I will update the logs later.
```

**Comment by chipweinberger** [comment]
i don't have this problem
