### ISSUE TITLE
[Feature]: stop the unnecessary Bluetooth scanning

### ISSUE THREAD

**Issue by tenSunFree** [chipweinberger/flutter_blue_plus#1012]
### FlutterBluePlus Version

1.33.2

### Flutter Version

3.19.6

### What OS?

Android

### OS Version

Android 14

### Bluetooth Module

FastConnect 6900

### What is your feature request?

When the user starts scanning Bluetooth devices, and then finds a Bluetooth device that he wants to connect to and clicks "CONNECT", if the scanning is still going on, he needs to stop the unnecessary Bluetooth scanning first, because the user has found the Bluetooth device he wants.
<img width="453" alt="2024-10-06_224126" src="https://github.com/user-attachments/assets/45d73ecf-c0a7-4aab-9fcc-9e178c9cdb1d">

### Logs

```shell
No log
```

**Comment by chipweinberger** [comment]
just call stopScan

some people connect to multiple devices at the same time 

so we can't just stop scanning by default
