### ISSUE TITLE
[Help]: IOS: FlutterBluePlus.startScan() automatically opens AppSettings

### ISSUE THREAD

**Issue by minhdang2803** [chipweinberger/flutter_blue_plus#1015]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.33.3

### Flutter Version

3.22.3

### What OS?

iOS

### OS Version

18.0

### Bluetooth Module

No 

### What is your problem?

The AppSettings is automatically open when startScan(), How can i prevent it from opening?

### Logs

```shell
No Logs
```

**Comment by chipweinberger** [comment]
please include screen recording

**Comment by minhdang2803** [comment]
https://drive.google.com/file/d/14oRYyo_k_-HZFcHy9x0wEZkIIAtNHJwo/view?usp=share_link

here is screen record, please check it for me

**Comment by minhdang2803** [comment]
> https://drive.google.com/file/d/14oRYyo_k_-HZFcHy9x0wEZkIIAtNHJwo/view?usp=share_link
> 
> here is screen record, please check it for me

When i tap on the "Bluetooth configuration" to open ble scanning page -> it invokes FlutterBlePlus.startScan(), then it automatically move to the AppSettings

**Comment by chipweinberger** [comment]
read the README

maybe your permissions are wrong
