### ISSUE TITLE
[Help]: Android - The FlutterBluePlus.isScanning's state is not change back to False when timeout for the first time user opens app

### ISSUE THREAD

**Issue by minhdang2803** [chipweinberger/flutter_blue_plus#1016]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.33.3

### Flutter Version

3.22.3

### What OS?

Android

### OS Version

Android 12 - Samsung Galaxy Note 10+

### Bluetooth Module

No

### What is your problem?

As the first time user scan blueetooth, the state of FlutterBluePlus.isScanning only change one time, the value is true, even thought after the timeout duration, it doesn't change the state back to false. This problem is gone when user kills the app and opens it again.

### Logs

```shell
No error logs
```

**Comment by chipweinberger** [comment]
the code looks fine to me.

please open a PR.
