### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by apiTpierson** [chipweinberger/flutter_blue_plus#1021]
### FlutterBluePlus Version

1.33.4

### Flutter Version

3.24.3

### What OS?

Android, iOS

### OS Version

10,20

### Bluetooth Module

ALL

### What is your feature request?

I want to connect to a non-detectable bluetooth like SSID connection with WIFI, is it possible ?

### Logs

```shell
No log
```

**Comment by chipweinberger** [comment]
not possible
