### ISSUE TITLE
Connected device delete from OS bluetooth device, again connect the same device unable to connect that device

### ISSUE THREAD

**Issue by balakrmu** [chipweinberger/flutter_blue_plus#1032]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.2

### Flutter Version

 3.24.2

### What OS?

Android

### OS Version

Android 12

### Bluetooth Module

_
### What is your problem?

Below mentioned state disconnected device unable to connect again.
If I check the connection State it shows the disconnected. 
D/[FBP-Android]( 2814): [FBP] onMethodCall: connect
D/[FBP-Android]( 2814): [FBP] already connecting

### Logs

```shell
D/[FBP-Android]( 2423): [FBP] onMethodCall: removeBond
W/[FBP-Android]( 2423): [FBP] already not bonded. When I call connect method it's show below
D/[FBP-Android]( 2423): [FBP] onMethodCall: connect
D/[FBP-Android]( 2423): [FBP] already connecting
I/flutter ( 2423): _connectAndBond() error: FlutterBluePlusException | createBond | fbp-code: 6 | device is not connected
```

**Comment by balakrmu** [comment]
Bluetooth Module 
-

**Comment by chipweinberger** [comment]
probably a problem with your peripheral BLE device.
