### ISSUE TITLE
[Help]: how to send messages using flutter_blue_plus between  two mobiles  ? 

### ISSUE THREAD

**Issue by coybitcom** [chipweinberger/flutter_blue_plus#1040]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

3

### Flutter Version

3

### What OS?

Android

### OS Version

android

### Bluetooth Module

android

### What is your problem?

how to send messages using flutter_blue_plus between  two mobiles  ? 

### Logs

```shell
how to send messages using flutter_blue_plus between  two mobiles  ?
```

**Comment by chipweinberger** [comment]
you cannot.

1 phone - peripheral mode
1 phone - central mode (FBP)
