### ISSUE TITLE
[Help]: empty scan results

### ISSUE THREAD

**Issue by Johnjson** [chipweinberger/flutter_blue_plus#1041]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

^1.32.12

### Flutter Version

Flutter version 3.19.5

### What OS?

Android

### OS Version

android 32

### Bluetooth Module

scan

### What is your problem?

<uses-feature android:name="android.hardware.bluetooth_le" android:required="false" />

<uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="30"/>

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="28" />

I can't scan nearby Bluetooth devices with this permission 。 But remove <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="30"/> android:maxSdkVersion="30" This part can search for Bluetooth devices. Why

### Logs

```shell
<startScan> args: {with_services: [], with_remote_ids: [], with_names: [], with_keywords: [], with_msd: [], with_service_data: [], continuous_updates: false, continuous_divisor: 1, android_legacy: false, android_scan_mode: 2, android_uses_fine_location: true}
D/[FBP-Android]( 3796): [FBP] onMethodCall: startScan
I/LifecycleTransaction( 3796): activityCallbacks TopResumedActivityChangeItem{onTop=false}
I/LifecycleTransaction( 3796): lifecycleStateRequest PauseActivityItem{finished=false,userLeaving=true,configChanges=0,dontReport=false}
I/TopResumedActivityChangeItem( 3796): execute start, ActivityClientRecord = ActivityRecord{79b9e5b token=android.os.BinderProxy@35852a7 {com.ql.star/com.example.ql.MainActivity}}
I/HwViewRootImpl( 3796): remove sceneId 10 topId: 0
I/flutter ( 3796): LogUtils d  2024-11-04 09:53:41   didChangeAppLifecycleState  inactive
I/LifecycleTransaction( 3796): activityCallbacks TopResumedActivityChangeItem{onTop=true}
I/TopResumedActivityChangeItem( 3796): execute start, ActivityClientRecord = ActivityRecord{79b9e5b token=android.os.BinderProxy@35852a7 {com.ql.star/com.example.ql.MainActivity}}
D/ActivityThread( 3796): Won't deliver top position change in state=4
I/RmeSchedManager( 3796): init Rme, version is: v1.0
I/LifecycleTransaction( 3796): activityCallbacks ActivityResultItem{resultInfoList=[ResultInfo{who=@android:requestPermissions:, request=1452, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }}]}
I/LifecycleTransaction( 3796): lifecycleStateRequest ResumeActivityItem{procState=2,updateProcState=true,isForward=true}
I/HwViewRootImpl( 3796): Add sceneId 3 topId: 0
D/ZrHung.AppEyeTransparentWindow( 3796): TransparentWindow mHungConfigStatus = 0,mHungConfigEnable = 1
```

**Comment by chipweinberger** [comment]
I think this is just a local bug in your setup. Other people seem to have no problems.

please reopen if you have more details.
