### ISSUE TITLE
[Help]: How to get type of device? Phone、PC、Printer?

### ISSUE THREAD

**Issue by mflutter3** [chipweinberger/flutter_blue_plus#1043]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.33.3

### Flutter Version

3.7.12 \ 3.24.4

### What OS?

All

### OS Version

iOS 18 \ Android 14

### Bluetooth Module

All

### What is your problem?

How to get type of device? Phone、PC、Printer?

### Logs

```shell
None
```

**Comment by chipweinberger** [comment]
you can't.

you can use "appearance value", but few devices actually set it.
