### ISSUE TITLE
[Question]: Why is the default MTU in the connect function 512?

### ISSUE THREAD

**Issue by mdtoom** [chipweinberger/flutter_blue_plus#1068]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.34.5

### Flutter Version

3.24.5

### What OS?

Android

### OS Version

Android 12

### Bluetooth Module

Not relevant

### What is your problem?

Why is the default MTU in the connect function 512 and not 517 as stated in for example https://developer.android.com/about/versions/14/behavior-changes-all#mtu-set-to-517

Is the header of 5 bytes added somewhere and is it not counted in MTU value?

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
512 is compatible with more devices.
