### ISSUE TITLE
[Help]: Is there a way to detect if scan has timed out/stopped?

### ISSUE THREAD

**Issue by naresh-intra** [chipweinberger/flutter_blue_plus#1076]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.33.4

### Flutter Version

3.5.3

### What OS?

All

### OS Version

IOS 18

### Bluetooth Module

Nordic

### What is your problem?

Is there a way to detect if scan has timed out/stopped? My scenario is to do repetitive restart of scan after a scan times out and if device is not found

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
yes, `FlutterBluePlus.isScanning`
