### ISSUE TITLE
[Help]: Suddenly the product disconnects. 

### ISSUE THREAD

**Issue by edwardocano** [chipweinberger/flutter_blue_plus#1079]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.34.5

### Flutter Version

3.24.3

### What OS?

iOS

### OS Version

iOS 18.1.1

### Bluetooth Module

espressif esp32

### What is your problem?

Suddenly and randomly the product disconnects from the app, is possible to know the reason of the disconection with the library?

### Logs

```shell
No logs, it happen suddenly.
```

**Comment by chipweinberger** [comment]
it will tell you in the logs

**Comment by edwardocano** [comment]
what will tell me the logs?
because when it disconnects says nothing
