### ISSUE TITLE
[Help]: How to use restoreState in the case of an Isolate?

### ISSUE THREAD

**Issue by luisfrossi** [chipweinberger/flutter_blue_plus#1082]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.34.5

### Flutter Version

3.10.5

### What OS?

iOS

### OS Version

18.2

### Bluetooth Module

NA

### What is your problem?

Hello, 

I have a quick question it is not clear to me. 

According to the documentation, when using the restoreState in an IOS device, it should be configured in starting point of the app. 

In my case I am running the Flutter Blue Plus inside an Isolate with flutter_foreground_task package. 

In this case, should I call this inside the starting point of the isolate or at the starting point of my app?

Thank you in advance!

### Logs

```shell
No logs
```

**Comment by chipweinberger** [comment]
duplicate. 

https://github.com/chipweinberger/flutter_blue_plus/issues/846
