### ISSUE TITLE
[Help]: iOS Background BLE scanning issue 

### ISSUE THREAD

**Issue by RohitMishra1402** [chipweinberger/flutter_blue_plus#1087]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.34.5

### Flutter Version

3.19.6

### What OS?

iOS

### OS Version

iOS 15

### Bluetooth Module

Don't Know

### What is your problem?

My app's main functionality is to scan for BLE (Bluetooth Low Energy) devices in the background. I am using this package, and it works well on Android for scanning BLE devices in both foreground and background modes. However, on iOS, it only works in the foreground and does not function in the background.

Could you please help me find a solution for this? I’ve tried multiple approaches, but none of them have worked so far.

It would be really helpful if you could suggest a solution or guide me on the right approach to make it work in the background on iOS.

Thank you!

### Logs

```shell
Package return empty list!
```

**Comment by chipweinberger** [comment]
duplicate. 

https://github.com/chipweinberger/flutter_blue_plus/issues/846
