### ISSUE TITLE
[Help]: 180F or 18f0 for iOS

### ISSUE THREAD

**Issue by solomon-okolie** [chipweinberger/flutter_blue_plus#1088]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.34.5

### Flutter Version

3.27.0

### What OS?

iOS

### OS Version

18.1.1

### Bluetooth Module

MP210

### What is your problem?

The docs mentions passing
````
List<Guid> withServices = [Guid("180F")];
````
for iOS but this did not work for me. passing Guid("18f0") did work.

### Logs

```shell
N/A
```

**Comment by chipweinberger** [comment]
0x180F is the battery service

**Comment by solomon-okolie** [comment]
@chipweinberger is there a place one can documentation of these numbers and what service they present?

**Comment by solomon-okolie** [comment]
No worries, I found https://www.bluetooth.com/wp-content/uploads/Files/Specification/Assigned_Numbers.html
