### ISSUE TITLE
[Feature]: transfer this repository to `https://github.com/chipweinberger`?

### ISSUE THREAD

**Issue by chipweinberger** [chipweinberger/flutter_blue_plus#732]
@boskokg, would you transfer this repository to my account?

I've done a lot of work on this repo, and would love for it to be on my profile.

`Settings -> General -> Scroll to bottom -> Transfer Ownership`

<img width="692" alt="Screenshot 2023-12-14 at 10 48 39 PM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/679747d3-3f59-47f8-967a-4123930e6ae6">

**Comment by wcoder** [comment]
As an option, a separate public organization may be suitable

**Comment by boskopopovic-sh** [comment]
@chipweinberger you can close this issue now :-)

**Comment by boskokg** [comment]
You can close this issue @chipweinberger
