### ISSUE TITLE
[Help]: Ble auto connection issue when bluetooth turn on/off in Android

### ISSUE THREAD

**Issue by NaynaAsodariya** [chipweinberger/flutter_blue_plus#886]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.32.7

### Flutter Version

3.19.5

### What OS?

Mac OS

### OS Version

Android 11

### Bluetooth Module

Not sure about it

### What is your problem?

Ble status connected
Turn off bluetooth 
Auto connection didn't work for Android only, it's working for iOS device

### Logs

```shell
In logs I can see that connect method but not connecting back

D/[FBP-Android](31094): [FBP] OnAdapterStateChanged: turningOn
D/[FBP-Android](31094): [FBP] OnAdapterStateChanged: on
D/[FBP-Android](31094): [FBP] onMethodCall: connect
D/BluetoothGatt(31094): connect() - device: _device_mac_address, auto: true, eattSupport: false
D/BluetoothGatt(31094): registerApp()
D/BluetoothGatt(31094): registerApp() - UUID=_uuid
```

**Comment by chipweinberger** [comment]
closing. no response.

**Comment by ImanGhasemiArani** [comment]
same issue. 
When the device is connected, turn off the bluetooth, after the device is 10 meters away, then turn on the bluetooth, then the device will not connect anymore, just restart the app to connect.

**Comment by chipweinberger** [comment]
open a PR thanks

**Comment by chipweinberger** [comment]
closing. no response.
