### ISSUE TITLE
[Feature]: Classic Bluetooth Support 

### ISSUE THREAD

**Issue by M-Tayyab-Mustafa** [chipweinberger/flutter_blue_plus#976]
### FlutterBluePlus Version

lastest

### Flutter Version

lastest

### What OS?

All

### OS Version

lastest

### Bluetooth Module

SSP or any Classic Bluetooth

### What is your feature request?

Please Add Classic Bluetooth Scanning and connecting and disconnecting. Because there are more than 70% of the world population currently uses classic Bluetooth and this package works only on the BLE.

### Logs

```shell
This is not the issue its a feature please add this.
```

**Comment by chipweinberger** [comment]
not going to happen
