### ISSUE TITLE
[Help]: Flutter Scanning Not Functioning in the Background (Android and iOS)

### ISSUE THREAD

**Issue by NaynaAsodariya** [chipweinberger/flutter_blue_plus#982]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.12

### Flutter Version

 3.24.0 

### What OS?

macOS

### OS Version

 iOS 17.5.1, macOS 14.5 

### Bluetooth Module

Build-in BLE module on iPhone 14 Pro Max.

### What is your problem?

scanResults are alway empty when app is in the background for both Android and IOS. 

Can anyone please help me to work ble scanning when app is in the background.

### Logs

```shell
App is in background mode

flutter: Scanning try: 2
flutter: Scan result is []
flutter: Scanning try: 3
flutter: Scan result is []
flutter: Scanning try: 4
flutter: Scan result is []
flutter: Scanning try: 5
flutter: Scan result is []

App is in Foreground mode

flutter: Scanning try: 6
flutter: Scan result is []
flutter: Scan result is [ScanResult{device: BluetoothDevice{remoteId: ---------, platformName: Lilio, services: null}, advertisementData: AdvertisementData{advName: Lilio, txPowerLevel: null, appearance: null, connectable: true, manufacturerData: {}, serviceData: {-----}, serviceUuids: []}, rssi: -55, timeStamp: 2024-08-28 12:15:28.668836}]
```

**Comment by chipweinberger** [comment]
https://github.com/chipweinberger/flutter_blue_plus/issues/846

https://github.com/chipweinberger/flutter_blue_plus/issues/930
