### ISSUE TITLE
[Help]: How can I track the fact that bluetooth devices are connected/disconnected to a smartphone, if this devices connect not from my app?

### ISSUE THREAD

**Issue by GAG888** [chipweinberger/flutter_blue_plus#987]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.32.12

### Flutter Version

3.10.6

### What OS?

Android

### OS Version

12

### Bluetooth Module

-

### What is your problem?

How can I track the fact that bluetooth devices are connected/disconnected to a smartphone, if this devices connect not from my app?_

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
check if it is in `systemDevices`

**Comment by efraespada** [comment]
@chipweinberger  @GAG888  The `systemDevices` is returning an empty list:

<img width="665" alt="Screenshot 2024-09-09 at 03 52 09" src="https://github.com/user-attachments/assets/49bc5a9e-aae6-45a0-a6f4-63c3b54eb842">

There are BT devices connected to my Android smartphone.
