### ISSUE TITLE
[Help]: When i tried to  send large file, it took much longer

### ISSUE THREAD

**Issue by YaoJuan** [chipweinberger/flutter_blue_plus#992]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.32.12

### Flutter Version

3.19.6

### What OS?

All

### OS Version

ios 17

### Bluetooth Module

esp32

### What is your problem?

When I try to send a file of about 7000 bytes using split write, it takes 6 to 8 seconds. Is this normal, or do you have any advice?

### Logs

```shell
no logs,  everything is ok but it just takes too long
```

**Comment by chipweinberger** [comment]
if on android, make sure to call `requestConnectionPriority`
