### ISSUE TITLE
[Help]: Possibility to connect to a hidden device

### ISSUE THREAD

**Issue by elvysferrari** [chipweinberger/flutter_blue_plus#995]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.12

### Flutter Version

3.10.5

### What OS?

Android

### OS Version

Android 13

### Bluetooth Module

ESP32, libraries BLEServer, BLEClient, BLEUtils, BLEScan, BLEAddress

### What is your problem?

Hi, how are you?

Is it possible for me to connect to a hidden device without having to pair the device?

I have an ESP32 configured to hide Bluetooth, is it possible for me to connect my cell phone to it without having to pair it? It would be similar to connecting via MAC Address on the old Bluetooth.

I'm using the last version of Flutter Blue Plus.

### Logs

```shell
No logs.
```

**Comment by chipweinberger** [comment]
> ESP32 configured to hide Bluetooth

what does that mean

**Comment by chipweinberger** [comment]
closing. not enough info.
