### ISSUE TITLE
[Help]: Auto connect issue

### ISSUE THREAD

**Issue by Mohd-ajmal** [chipweinberger/flutter_blue_plus#998]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.31.7

### Flutter Version

3.16.3

### What OS?

Android

### OS Version

10

### Bluetooth Module

nRF52832 SoC

### What is your problem?

I am facing an issue with auto connect. It works fine if our mobile’s Bluetooth version is nearly 5.3 or 5.2 but for version 5.0 mobile is taking too long to connect for sometimes it won’t connect, so my question is how we can detect is our mobile is already trying to connect with ble device currently or how we can provide solution for this type is situations.

### Logs

```shell
nil
```

**Comment by chipweinberger** [comment]
talk to Google / Android people

FBP does not control how autoconnect works
